<a href="https://colab.research.google.com/github/pikey-msc/CursoDF/blob/master/M%C3%B3dulo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ambiente colaborativo

Es posible importar archivos de fuentes como github, gdrive y de local.

In [0]:
# De google drive
from google.colab import drive
drive.mount('/content/drive')

In [2]:
# De local
from google.colab import files
data=files.upload()

Saving Temario Módulo 1.xlsx to Temario Módulo 1.xlsx


In [16]:
# De github
!git clone 'https://github.com/pikey-msc/CursoDF'

fatal: destination path 'CursoDF' already exists and is not an empty directory.


Lenguje Python


In [0]:
# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
# Leer archivos
data = pd.read_excel('/content/CursoDF/M1/Temario Módulo 1.xlsx')
print("data", data)

data     Unnamed: 0 Módulo 1              Unnamed: 2
0          NaN        1  Conceptos básicos de R
1          NaN      1.1   Ambiente colaborativo
2          NaN    1.1.1         Lenguaje Python
3          NaN    1.1.2              Lenguaje R
4          NaN      1.2     Operaciones básicas
5          NaN      1.2   Creación de variables
6          NaN      1.3     Vectores y matrices
7          NaN      1.4               DatFrames
8          NaN      1.5  Estructuras primitivas
9          NaN    1.5.1            if-then-else
10         NaN    1.5.2                     for
11         NaN    1.5.3                   while
12         NaN      1.6     Apply-Sapply-Lapply


## El lenguaje R en el ambiente colaborativo

In [19]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [20]:
%%R
#Instalamos las bibliotecas que utilizaremos
install.packages("MPDiR")    # Donde estan los datos Chromatic
install.packages("dplyr")    # Para manipulación de datos
install.packages("ggplot2")  # Para poder gráficar
install.packages("lattice")  # Para poder graficar xyplot y condicionados
install.packages("readxl")   # Para abrir archivos en excel
install.packages("MASS")     # Para hacer regresiones de tipo binomial negativa
install.packages("caret")
install.packages("caret")    # Permite evaluar los modelos de regresion
install.packages("plotly")   # Para hacer gráficos dinámicos
install.packages("mlbench")  # Permite obtener los datos de Sonar
install.packages("e1071") # Solucion error caret
install.packages("caTools") # Permite calcular el score AUC de la Curva ROC
install.packages("matlib")

/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://cran.rstudio.com/src/contrib/MPDiR_0.1-16.tar.gz'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Content type 'application/x-gzip'
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 171284 bytes (167 KB)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: =
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/di

In [0]:
%%R
library(MPDiR)   # Donde estan los datos Chromatic
library(dplyr)   # Para manipulación de datos
library(ggplot2)  # Para poder gráficar
library(lattice)  # Para poder graficar xyplot y condicionados
library(readxl)  # Para abrir archivos en excel
library(MASS)    # Para hacer regresiones de tipo binomial negativa
library(caret)
library(caret)   # Permite evaluar los modelos de regresion
library(plotly)  # Para hacer gráficos dinámicos
library(mlbench)  # Permite obtener los datos de Sonar
library(e1071)  #Solucion error caret
library(caTools) # Permite calcular el score AUC de la Curva ROC
library(matlib)

Operaciones básicas

In [23]:
%%R
5 + 5

[1] 4


In [24]:
%%R
5 - 5

[1] 0


In [25]:
%%R
3 * 5

[1] 15


In [26]:
%%R
(5 + 5) / 2

[1] 5


In [27]:
%%R
2^5

[1] 32


In [28]:
%%R

28%%6

[1] 4


In [29]:
%%R
a<-5
b<-100
20->c
a+b-c

[1] 85


In [0]:
%%R
complex<-10-5i

In [33]:
%%R
class(complex)

[1] "complex"


## Creación de vectores y matrices

Función c() para crear vectores
Esta función crea vectores a partir de elementos individuales, esto quiere decir, que el usuario intruduce dichos valores. No importa que los vectores guarden la misma información, cada uno de ellos se diferencia por el nombre de asignación. Esta función concatene varios elementos del mismo tipo, cuando se imprime el vector se hace en un renglón que comienza con el símbolo ‘[1]’, indicando con ello que el primer elemento del renglón corresponde al primer elemento del vector.

In [36]:
%%R
a<-c(5,10,15,20)
print(a)
print(class(a))
c(4,8,12,16)->b
print(b)
d=c(5,10,15,20)
print(d)
print(class(d))

[1]  5 10 15 20
[1] "numeric"
[1]  4  8 12 16
[1]  5 10 15 20
[1] "numeric"


Ejercicio. Construir un objeto a que contenga los elementos 2 y 4. 

1.   Construir un objeto a que contenga los elementos 2 y 4. También hacerlo para b, pero en ese caso que contenga del 2 al 4.
2.   Crear un vector que contenga una secuencia de 5 en 5, partiendo del número 5 al 35 y otra de 3 en 3, partiendo del 7 hasta el 80 (utilice la función seq).

Matrices. Las matrices también se pueden crear de manera flexible con función *matrix*, la cual permite alterar la secuencia por default de armado de la matriz; esto es, poder armar la matriz por filas y no por columnas.

In [0]:
%%R
#mat2 <- matrix(21:60, nrow = 4, ncol = 5, byrow = TRUE)

mat2 <- matrix(21:60, nrow = 5, ncol = 4, byrow = TRUE)

#mat2 <- matrix(21:60, nrow = 5, ncol = 4)

In [44]:
%%R
print(mat2)

     [,1] [,2] [,3] [,4]
[1,]   21   22   23   24
[2,]   25   26   27   28
[3,]   29   30   31   32
[4,]   33   34   35   36
[5,]   37   38   39   40


In [0]:
%%R
rownames(mat2)<- c("ID Alumno","ID Profesor","ID Administrativo","ID Investigador","ID Interino")
colnames(mat2)<- c("Tipo A","Tipo B","Tipo C","Tipo D")

In [46]:
%%R
mat2

                  Tipo A Tipo B Tipo C Tipo D
ID Alumno             21     22     23     24
ID Profesor           25     26     27     28
ID Administrativo     29     30     31     32
ID Investigador       33     34     35     36
ID Interino           37     38     39     40


Ejercicio.

1.   Crear una matriz que muestre las ganancias en millones de dólares dentro y fuera de E.U.A, de las siguientes películas: Episodio IV (E.U.A=460, O.P=314), Episodio V (E.U.A=290, O.P=247) y Episodio VI (E.U.A=309, O.P=165)
2.   Asignar nombre a filas y columnas a la matriz star_wars_matriz



Funciones rbind() y cbind()


In [47]:
%%R
mat3 <- rbind(c(1.5, 2.7, -3.9), c(1.4, -1.1, 2.1)) 
print(mat3)
mat4<- cbind(c(2,4,6,8), c(1,0.5,1,0.3), c(5,8,0,1))
print(mat4)

     [,1] [,2] [,3]
[1,]  1.5  2.7 -3.9
[2,]  1.4 -1.1  2.1
     [,1] [,2] [,3]
[1,]    2  1.0    5
[2,]    4  0.5    8
[3,]    6  1.0    0
[4,]    8  0.3    1


Listas
Una lista en R permite reunir una variedad de objetos bajo un nombre (es decir, el nombre de la lista) de una manera ordenada. Estos objetos pueden ser matrices, vectores, marcos de datos, incluso otras listas, etc. No se requiere que estos objetos estén relacionados entre sí de ninguna manera.

Una lista, de la clase list(), es una clase de datos que puede contener cero o más elementos, cada uno de los cuales puede ser de una clase distinta.

Por ejemplo, se puede concebir una lista para representar una familia: mamá, papá, años de casados, hijos, y edad de los hijos. Esto quiere decir, que dicha lista tiene información alfanumérica.

In [49]:
%%R
familia1 <- list("Gabriela", "Mauricio", 25, c("Alain", "Priscila"), c(18,15))
print(familia1)
familia1 <- list(Madre="Gabriela", Padre="Mauricio", casados=25, Hijos=c("Alain", "Priscila"), Edades=c(18, 15))
print(familia1)
#Las listas no serían de mucha utilidad sin la posibilidad de tener acceso a sus elementos individuales. 
#El lenguaje, provee de este acceso mediante tres operadores, : [ ], [[ ]], y $.

[[1]]
[1] "Gabriela"

[[2]]
[1] "Mauricio"

[[3]]
[1] 25

[[4]]
[1] "Alain"    "Priscila"

[[5]]
[1] 18 15

$Madre
[1] "Gabriela"

$Padre
[1] "Mauricio"

$casados
[1] 25

$Hijos
[1] "Alain"    "Priscila"

$Edades
[1] 18 15



# Dataframes


Es un tipo de variable cuyos componentes pueden ser vectores, matrices o factores, con la única excepción de que las longitudes, o número de renglones, en el caso de matrices, deben coincidir con todos los componentes. La apariencia de un data frame es de una tabla, una forma de crearlos es mediante la función data.frame()

In [50]:
%%R
CDMX<-data.frame(Nombre=c("Alondra","Berenice","Jorge","Melina","Eleazar"),Edad=c(37,34,40,25,29),Delegacion=c("Xochimilco","Iztacalco","Iztapalapa","Tlalpan", "Coyoacan"),Sexo=c("M","M","H","M","H"),Casado=c(F,T,T,F,T))
CDMX

    Nombre Edadd Delegacion Sexo Casado
1  Alondra    37 Xochimilco    M  FALSE
2 Berenice    34  Iztacalco    M   TRUE
3    Jorge    40 Iztapalapa    H   TRUE
4   Melina    25    Tlalpan    M  FALSE
5  Eleazar    29   Coyoacan    H   TRUE


In [0]:
%%R
# #Fila 4
# persona4<-CDMX[4,]
# persona4
# # Columna 3
# columna3<-CDMX[,3]
# columna3

# # También se puede llamar a la columna colocando su nombre

# columna3<-CDMX[,"Delegacion"]
# columna3
# # Sexo persona 2
# persona2_sex<-CDMX[2,4]
# persona2_sex
# # Estado civil de la persona 3
# persona3_edocivil<-CDMX[3,5]
# persona3_edocivil
# # Delgación de la persona 1
# persona1_delega<-CDMX[1,3]
# persona1_delega
# # Nombre, edad y delgación de la persona 5
# persona5_nom_edad_dele<-CDMX[5,1:3]
# persona5_nom_edad_dele

# Estructuras de control y manejo de datos


En R son semejantes a la de otros lenguajes de programación, la construcción en sí misma regresa un valor, que puede, si se quiere, ser asignado a una variable o utilizado de otras maneras.

La construcción de un IF admite una sola expresión, pero esta puede ser compuesta, la cual se construye con llaves { }, y las expresiones en su interior, separadas ya sea por el cambio de renglón o por ‘;’.

In [0]:
%%R
num = 2
if (num > 25) 
print("SI MAYOR")

# num = 12
# if (num > 25) 
# print("SI MAYOR")

# num = 22
# if (num > 25) 
# print("SI MAYOR")

# num = 32
# if (num > 25) 
# print("SI MAYOR")

In [54]:
%%R
# Función que determina si un entero es mayor que 8
 fun1 <- function(x){
 if(x >= 8){
 print("x es mayor o igual que 8")}
 else{
 print("x es menor que 8")}
 }
fun1(4)
fun1(8)
fun1(15)

[1] "x es menor que 8"
[1] "x es mayor o igual que 8"
[1] "x es mayor o igual que 8"


Crear un IF donde se muestre que cualquier número entero menor a 10 tiene un rango bajo, mayor a 10 pero menor a 20 pertenece a un rango medio, y si es mayor a 20 entonces tendrá un rango alto.

In [0]:
%%R
norpa <- function(x){
    if (x < 10) {
        print("RANGO BAJO")
        print("primer renglon")
        } else
        if ( x >=10 && x <= 20) {
            print("segundo renglon")
            print("RANGO MEDIO")
            } else {
                print("RANGO ALTO")
}
}

In [61]:
%%R
norpa(1)
norpa(10)
norpa(50)
norpa(28)

[1] "RANGO BAJO"
[1] "primer renglon"
[1] "segundo renglon"
[1] "RANGO MEDIO"
[1] "RANGO ALTO"
[1] "RANGO ALTO"


El número de veces que se repite la expresión o expresiones englobadas en la instrucción, puede estar explícita en ella misma.

In [62]:
%%R
for (i in 1:15) print(i^2)

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25
[1] 36
[1] 49
[1] 64
[1] 81
[1] 100
[1] 121
[1] 144
[1] 169
[1] 196
[1] 225


In [70]:
%%R
letras <- c("C", "A", "L", "O", "R")
for (i in letras) {
print(i)
}

[1] "C"
[1] "A"
[1] "L"
[1] "O"
[1] "R"


In [68]:
%%R
letras[1]

[1] "C"
